[tool.bumpversion]
current_version = "0.1.0"
commit = true
tag = true
tag_name = "v{new_version}"
message = "chore: bump version to {new_version}"
tag_message = "Release {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/quote0_client/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
